include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    unawaited_futures: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    discarded_futures: false
