name: jobdi
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.8+9
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  intl: ^0.20.2
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  smart_auth: ^3.2.0

dev_dependencies:
  freezed: ^3.2.3
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
          weight: 100

        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
          weight: 300

        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
          weight: 400

        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
          weight: 500

        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
          weight: 700

        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
          weight: 900
