// /// Flutter icons JobdiIcon
// /// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  JobdiIcon
// ///      fonts:
// ///       - asset: fonts/JobdiIcon.ttf
// ///
// ///
// ///
// // ignore_for_file: constant_identifier_names

// library;

// import 'package:flutter/widgets.dart';

// class JobdiIcon {
//   JobdiIcon._();

//   static const _kFontFam = 'JobdiIcon';

//   static const IconData icon_arrow_left = IconData(
//     0xe800,
//     fontFamily: _kFontFam,
//   );
//   static const IconData icon_close = IconData(0xe801, fontFamily: _kFontFam);
//   static const IconData icon_phone = IconData(0xe802, fontFamily: _kFontFam);
// }
